# Estudos com o número primo

In [1]:
import pandas as pd
import numpy as np

In [36]:
# variável utililzada em todos os testes
n = 10

In [6]:
# ESTUDOS E TESTES [lista]
# LISTAR NÚMEROS PRIMOS com numpy
# ---
# by geanclm in 03/03/2022
# ---
primos = []
for i in np.arange(n):
    if i > 1:
            for j in range(2,i):
                if(i%j==0):
                    break
            else:
                primos.append(i)
# ---
print (primos)
print ('-'*33)
print (type(primos))
print (f'quantidade de valores: {len(primos)}')

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
---------------------------------
<class 'list'>
quantidade de valores: 25


In [52]:
# ESTUDOS E TESTES (array)
# LISTAR NÚMEROS PRIMOS com numpy
# ---
# by geanclm in 21/04/2022 at 11:47h
# ---
numbers = []
primos = [2]
pares = (np.arange(2,n+1)[np.where((np.arange(2,n+1))%2==0)])
ímpares = (np.arange(0,n+1)[np.where((np.arange(0,n+1))%2!=0)])
# sr = int(n**(0.5)) # condição da raíz quadrada

# for i in (np.array([x for x in range(2, n) if x%2!=0])):  # restrição ao universo dos ímpares para otimizar esforço computacional

# refinamento no código para selecionar somente os ímpares com numpy
# by geanclm in 16/05/2022 at 20:24h
for i in (np.arange(2,n+1)[np.where((np.arange(2,n+1))%2!=0)]):
    
    if i > 1:
        numbers.append(i)
        for j in range(2,i):
            if(i%j==0):
                break
        else: 
            primos.append(i)
# ---
arrayPrimos = np.array(primos)
# ---
print (ímpares)
print (type(ímpares))
print (f'Qtd ÍMPARES na amostra: {len(ímpares)}')
print ('-'*33)
print (arrayPrimos)
print (type(arrayPrimos))
print (f'Qtd PRIMOS encontrados: {len(arrayPrimos)}')
# print ('-'*33)
# print ('''Observação: O número "2" é o único primo par
# e por isso é considerado por padrão no início da série.''')
print ('-'*33)
df = pd.DataFrame({'amostra':[n],
                    'pares':[len(pares)],
                    'ímpares':[len(ímpares)],
                    'primos':[len(arrayPrimos)]},
                   index=['0'])
df

[1 3 5 7 9]
<class 'numpy.ndarray'>
Qtd ÍMPARES na amostra: 5
---------------------------------
[2 3 5 7]
<class 'numpy.ndarray'>
Qtd PRIMOS encontrados: 4
---------------------------------


amostra  pares  ímpares  primos
0       10      5        5       4

In [10]:
import time

In [24]:
# VERIFICADOR DE NÚMERO PRIMO - contando o tempo de execução
# Objetivo: otimizar a verificação de um número primo
# by geanclm in 12/03/2022 at 19:55h

# 1 - utilizar o recurso da raiz quadrada
# 2 - reduzir o range ao universo dos ímpares
# 3 - verificar tempo de execução do script
# 4 - testar a divisão pelos próprios números primos até a condição de divisor >= quociente
# 5 - números primos para testar: 99991, 4999, 30011

ti = time.time() # registrar o tempo incial de execução
n = 99991999913131313 # O número 99991999913131313 NÃO é primo

def primo(n):
    r = int(n**(0.5))
    for i in ([x for x in range(2, r+1) if x%2!=0 and x%3!=0]):
#         print (i, end=' ') # a verificação está passando por números pares e não precisa!!!!
        if (n % i == 0):
            return False
    return True
# time.sleep(2)
# tf = time.time() # registrar o tempo final de execução

# n = int(input("número para verificar: "))

if primo(n):
    print(f'''
    O número {n} é PRIMO''')
else:
    print(f'''O número {n} NÃO é primo''')
    
tf = time.time() # registrar o tempo final de execução
print(f'''Tempo total de execução: {tf - ti} segundos''')

O número 999919 NÃO é primo
Tempo total de execução: 0.0 segundos


In [33]:
# em estudo...
# ausência de dados no resultado final
# testar redução de amostras numéricas para reduzir esforço computacional
# array = np.array([x for x in range(2, n) if x%2!=0 and x%3!=0 and x%5!=0])
array = np.array([x for x in range(2, n) if x%2!=0])
print(array)

[  3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37
  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73
  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109
 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143 145
 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181
 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215 217
 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251 253
 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287 289
 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323 325
 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359 361
 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395 397
 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431 433
 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467 469
 471 473 475 477 479 481 483 485 487 489 491 493 49

In [ ]:
# resultado da expressão geradora de números primos
# 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59

In [32]:
# ESTUDOS com o numpy
# listando uma sequência de números primos com o numpy
# by geanclm in 21/04/2022 at 10:50h
a = np.arange(0,1000)
def is_prime(n):
    if n%2 == 0 and n > 2: 
        return False
    elif n <= 0 or n == 1: 
        return False
    return all(n%i for i in range(3, int(n**1/2)+1, 2))
np.extract(np.vectorize(is_prime)(a),a)

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569,
       571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643,
       647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733,
       739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823,
       827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
       919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997])

In [34]:
# testes de otimização
for i in ([x for x in range(3, 50+1) if x%2!=0 and x%3!=0]):
    print (i, end=' ')

5 7 11 13 17 19 23 25 29 31 35 37 41 43 47 49 